services:
  backend:
    build:
      context: .
      args:
        BAL_VERSION: "2201.7.2"
    image: qhana-backend
    volumes:
      - ./experimentData:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      QHANA_URL_MAPPING: '{"^http://localhost": "http://host.docker.internal", "^https://localhost": "https://host.docker.internal"}' # FIXME patterns can be combined to '{"(?<=^|https?://)localhost": "host.docker.internal"}' once ballerina supports positive lookbehind (https://github.com/ballerina-platform/ballerina-lang/issues/40480)
      QHANA_DB_TYPE: 'mariadb'
      QHANA_DB_HOST: 'db:3306'
      QHANA_DB_NAME: 'QHAnaExperiments'
      QHANA_DB_USER: 'qhana'
      QHANA_DB_PASSWORD: 'qhana'
      QHANA_HOST: 'http://localhost:9090'
      QHANA_PLUGIN_RUNNERS: '["http://localhost:5005/"]'
      QHANA_PLUGINS: '[]'
      WAIT_HOSTS: 'db:3306'
      OS_TYPE: 'linux'
    ports:
      - 9090:9090
    depends_on:
      - db
  db:
    image: "mariadb:10"
    volumes:
      - ./mariadb-init.sql:/docker-entrypoint-initdb.d/mariadb-init.sql
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: 'QHAnaExperiments'
      MARIADB_ROOT_PASSWORD: 'qhana_root'
      MARIADB_USER: 'qhana'
      MARIADB_PASSWORD: 'qhana'
